//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int Attendance_ID { get; set; }
        public Nullable<System.DateTime> first_in { get; set; }
        public Nullable<System.DateTime> last_out { get; set; }
        public System.DateTime date { get; set; }
        public string status { get; set; }
        public int Employee_emp_id { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
