//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_designation_history
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public int Employee_emp_id { get; set; }
        public int Designation_Designation_id { get; set; }
    
        public virtual Designation Designation { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
