//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leave
    {
        public int leave_id { get; set; }
        public System.DateTime from_date { get; set; }
        public System.DateTime to_date { get; set; }
        public string leave_description { get; set; }
        public string leave_status { get; set; }
        public int Leave_type_type_id { get; set; }
        public int Employee_emp_id { get; set; }
        public double from_session { get; set; }
        public double to_session { get; set; }
        public Nullable<System.DateTime> approval_date { get; set; }
        public string apply_to { get; set; }
        public Nullable<System.DateTime> Submited_date { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Leave_type Leave_type { get; set; }
    }
}
