//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leave_history
    {
        public int ID { get; set; }
        public int Employee_emp_id { get; set; }
        public double Leaves_remaining { get; set; }
        public int Leave_type_type_id { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Leave_type Leave_type { get; set; }
    }
}
